# Generated by Django 4.0.4 on 2022-11-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='score',
            new_name='fans',
        ),
    ]
