# Generated by Django 4.0.4 on 2022-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_rename_score_player_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='jump',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shotForce',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=200),
        ),
    ]
