# Generated by Django 4.0.4 on 2022-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0003_player_exp_player_jump_player_level_player_shotforce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='multiplier',
            field=models.IntegerField(default=0),
        ),
    ]
