# Generated by Django 4.0.4 on 2022-11-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0004_player_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
