# Generated by Django 4.0.4 on 2022-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0005_alter_player_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='multiplier',
            new_name='point',
        ),
        migrations.AlterField(
            model_name='player',
            name='jump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='shotForce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
