# Generated by Django 4.0.4 on 2022-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
