# Generated by Django 4.0.4 on 2022-11-26 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_gameinfo_level_gameinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
